### ISSUE TITLE
AGN Science MVP

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#140]
Demonstrate a scientifically productive workflow from the Time-Domain MVP project. Using time-domain data from Panstarrs, ZTF, and potentially SDSS (effectively using their measurements as a single time-domain point...), run the JAX code through the combined lightcurves. This will expose a lot of open issues and problems, especially at scale, which should be incredibly useful for getting TAPE to where we want it to be.

**Comment by nevencaplar** [comment]
We are capturing these general issues outside of github now
