### ISSUE TITLE
Save Ensemble to Parquet

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#151]
Saving the ensemble to parquet would be useful for saving state. The object and source tables should probably be saved as two separate parquet files.

Neccessary Components:

- [x] ensemble.save_ensemble() function; Saves an Ensemble to disk, with subdirectories for object and source partitions. Option (perhaps on by default) to include all result frames, or just a subset of result frames
- [x] ensemble.from_ensemble() function; Reads the directory structure established by save (parquet-like) and loads into a new ensemble, I think this will need to be a separate function from read_parquet to handle the addition of many result tables implicitly
- [x] from_ensemble(); An Ensemble constructor function that bypasses ensemble initialization
- [x] unit tests; with some consideration to how we test the save function within the actions framework. Does it just purge any created files automatically? _Edit: No it doesn't. Resolved this by using pytest with pathlib.Path temporary directories_
- [x] documentation; this feature will be important enough to need some documentation beyond just autoapi.

Non-critical Components:
- [x] Potentially save the column mapper and load it within the save/load internals. Avoid needing to specify the column mapper in the load.

Open Questions/Issues:
* Schema error with saving Stetson_J result frames to parquet. These frames have a dictionary result column, it may be that there's a simple schema argument to pass, but this would also be resolved by just making stetson_J return a column per band (as has been talked about for a while). Given that stetson_J is really just a tester function for us, I'm opting to not spend time on getting it working.

**Comment by hombit** [comment]
We should also save result frames
