### ISSUE TITLE
EnsembleFrame Refactor Milestone 1: EnsembleFrame Class Creation

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#192]
#191 Milestone 1 focuses on the creation of the EnsembleFrame class, separate from the Ensemble class. The EnsembleFrame class will be a subclass of Dask's Dataframe class.

In addition, it should have at least the following additional properties:
* EnsembleFrame.label: Some label to identify the frame from the Ensembles perspective, object and source are fixed, but otherwise the user is free to set however they wish
* EnsembleFrame.ensemble: A link to the Ensemble that contains this frame, needed to update the ensemble using EnsembleFrame.update_ensemble()
* EnsembleFrame.links [NOT CRUCIAL FOR MILESTONE 1]: Not 100% sure about this, this would be some data structure that tracks linkages between EnsembleFrames, for example the links between Object and Source in terms of update n_obs, co-filtering by IDs, etc. 
And the following additional functions:
* EnsembleFrame.update_ensemble() [MAY NEED TO WAIT FOR MILESTONE 2]: Updates the Ensemble object with the current state of the EnsembleFrame object, importantly returns an ensemble object to allow command chaining. 
* [Any Astro specific operations]: Things like flux to magnitude conversion functions, anything domain specific beyond the scope of a Dask dataframe we would also build into the EnsembleFrame

**Comment by wilsonbb** [comment]
The PRs [https://github.com/lincc-frameworks/tape/pull/209](#209) and [https://github.com/lincc-frameworks/tape/pull/212](#212) close this issue.
