### ISSUE TITLE
Simplify Ensemble creation

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/tape#199]
It looks like all `Ensemble.from_*` methods could be wrapped with `@classmethod` to make them constructors. Also we can follow `pandas` / `polars` / `numpy` practice and make all this constructors to be stand-alone functions, which would make Ensemble initialization less wordy.

**Comment by wenneman** [comment]
In order to not break any current Tape usage, I've introduced new "read_" static class methods that essentially wraps the existing Ensemble constructor and call the corresponding "from_" method to populate the Ensemble object. This is similar to what Pandas did to deprecate their "from" methods and replace them with "read" methods which return a new dataframe instance.

**Comment by hombit** [comment]
@wenneman I agree, but I would go further and make them top-namespace-level functions

**Comment by wenneman** [comment]
The classmethod allows a user to call a single static read method which will create and return a new Ensemble object. For example:
`pd_ens = Ensemble.read_pandas_dataframe(...)`
`hips_ens = Ensemble.read_hipscat(...)`

As far as namespace goes, I believe users are importing Ensemble from the tape namespace which enables access to these static constructors via the Ensemble class. 

Are your proposing a namespace different from tape for these static read constructors?

**Comment by hombit** [comment]
In some sense, static method is just a function in some class' namespace. What I propose is having a function `tape.read_hipscat` instead of `tape.Ensemble.read_hipscat`, just like pandas has `pandas.read_csv` and numpy has `numpy.array`

**Comment by wenneman** [comment]
That makes sense, and helps with consistency. I'll move these static constructors from the "tape.Ensemble" namespace to the "tape" namespace.
