### ISSUE TITLE
Base class for TAPE built-in analysis functions

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/tape#200]
Currently, `Ensemble.batch` recognizes TAPE functions by `.__name__` attribute:
https://github.com/lincc-frameworks/tape/blob/0a2957831fb83ebd7fab27b99da812ead10674e5/src/tape/ensemble.py#L721-L722

This approach has some disadvantages:
1. After a while we would have more built-in functions which would occupy the namespace and prevent user from implementing a function of the same name
2. It requires the usage of local variables `known_cols` and and `known_meta` containing some knowledge about the functions implemented in a very different part of the code, so it could cause maintenance issues 
3. This check fails if input callable has no `__name__` attribute

The last one is minor, but it is how I have actually found it:

```python
import light_curve as licu
import tape

ens = tape.Ensemble().from_dataset('s82_qso')
ens.batch(licu.Duration(), ens._time_col, ens._flux_col, ens._err_col)
```

```
AttributeError: 'light_curve.light_curve_ext.Duration' object has no attribute '__name__'
```

I believe that introduction of an abstract base class for TAPE analysis functions would solve these issues and give an optional interface for user functions:
1. We can easily check if input is a TAPE function with `isinstance`
2. We can handle `known_cols` and `known_meta` inside function 
3. User could inherit this class to create user-defined functions, or just use the interface already exists with `Ensemble.batch(func, *args)` with no worry about function name
4. This would allow creation of parametric functions

**Comment by dougbrn** [comment]
We talked about this a bit, I'm strongly in favor of the proposal.
