### ISSUE TITLE
macOS warnings when using TAPE

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/tape#208]
When I start a script using TAPE on macOS it gives me a batch of warnings saying "Do you want the application
"Python.app" to accept incoming network connections?". Does it mean that by default `dask` tries to open a port on `0.0.0.0`? Could we prevent it doing that?

<img width="524" alt="Screenshot 2023-08-25 at 09 50 55" src="https://github.com/lincc-frameworks/tape/assets/1784493/5408fc9a-261e-4510-a526-b6fa75a9046c">

**Comment by dougbrn** [comment]
I've personally never encountered this on my Mac, but it does look to be deeper down than Dask itself: https://stackoverflow.com/questions/34760163/how-to-allow-python-app-to-firewall-on-mac-os-x

**Comment by hombit** [comment]
I have firewall turned on in the settings
<img width="827" alt="image" src="https://github.com/lincc-frameworks/tape/assets/1784493/c921a38a-32fa-43fe-8703-006ee1bc7a2a">

For me it looks like TAPE (probably via Dask) is trying to open port to the outer world, which is a security concern and not what user expects it to do. I can reproduce the same message when I start a http server listening `0.0.0.0`, but not `127.0.0.1` (run it in an empty directory):
```
# No warning
python3 -m http.server -b 127.0.0.1
# warning
python3 -m http.server -b 0.0.0.0
```

**Comment by dougbrn** [comment]
Interesting, my understanding of Dask was that it is just spinning up a localhost, and shouldn't be opening an external port.

**Comment by hombit** [comment]
It is what I have for an IPython session, where I've just run `ens = Ensemble()`: it opened port 8787 for the outside world.

```bash
lsof -i -n -P | grep 4051
Python     4051 hombit   15u  IPv4 0x437ad27cd7ea1ebb      0t0  TCP *:8787 (LISTEN)
Python     4051 hombit   16u  IPv6 0x437ad2780ab78143      0t0  TCP *:8787 (LISTEN)
Python     4051 hombit   17u  IPv4 0x437ad27cd7e87b2b      0t0  TCP 127.0.0.1:59036 (LISTEN)
Python     4051 hombit   19u  IPv4 0x437ad27cd594c63b      0t0  TCP 127.0.0.1:59037->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   20u  IPv4 0x437ad27cd7e9fd8b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59037 (ESTABLISHED)
Python     4051 hombit   21u  IPv4 0x437ad27cd597debb      0t0  TCP 127.0.0.1:59038->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   22u  IPv4 0x437ad27cd7e93b2b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59038 (ESTABLISHED)
Python     4051 hombit   23u  IPv4 0x437ad27cd5951ebb      0t0  TCP 127.0.0.1:59039 (LISTEN)
Python     4051 hombit   24u  IPv4 0x437ad27cd7e5276b      0t0  TCP 127.0.0.1:59040 (LISTEN)
Python     4051 hombit   25u  IPv4 0x437ad27cd7e5914b      0t0  TCP 127.0.0.1:59041 (LISTEN)
Python     4051 hombit   26u  IPv4 0x437ad27cd595089b      0t0  TCP 127.0.0.1:59042 (LISTEN)
Python     4051 hombit   27u  IPv4 0x437ad27cd59513ab      0t0  TCP 127.0.0.1:59043->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   28u  IPv4 0x437ad27cd7e95c5b      0t0  TCP 127.0.0.1:59044->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   29u  IPv4 0x437ad27cd7e8e9cb      0t0  TCP 127.0.0.1:59045->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   30u  IPv4 0x437ad27cd7e553ab      0t0  TCP 127.0.0.1:59046->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   31u  IPv4 0x437ad27cd7e8bd8b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59043 (ESTABLISHED)
Python     4051 hombit   32u  IPv4 0x437ad27cd7e8c89b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59044 (ESTABLISHED)
Python     4051 hombit   33u  IPv4 0x437ad27cd7e8d3ab      0t0  TCP 127.0.0.1:59036->127.0.0.1:59045 (ESTABLISHED)
Python     4051 hombit   34u  IPv4 0x437ad27cd7e9a9cb      0t0  TCP 127.0.0.1:59036->127.0.0.1:59046 (ESTABLISHED)
Python     4051 hombit   84u  IPv4 0x437ad27cd7e4fb2b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59055 (ESTABLISHED)
Python     4051 hombit   87u  IPv4 0x437ad27ccf68c63b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59056 (ESTABLISHED)
Python     4051 hombit   88u  IPv4 0x437ad27ccf68d14b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59057 (ESTABLISHED)
Python     4051 hombit   91u  IPv4 0x437ad27ccf68e76b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59058 (ESTABLISHED)
Python     4051 hombit   92u  IPv4 0x437ad27ccf6913ab      0t0  TCP 127.0.0.1:59059->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   93u  IPv4 0x437ad27ccf6929cb      0t0  TCP 127.0.0.1:59036->127.0.0.1:59059 (ESTABLISHED)
Python     4051 hombit   94u  IPv4 0x437ad27ccf69089b      0t0  TCP 127.0.0.1:59060->127.0.0.1:59036 (ESTABLISHED)
Python     4051 hombit   95u  IPv4 0x437ad27cd596bb2b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59060 (ESTABLISHED)
Python     4051 hombit   96u  IPv4 0x437ad27cd596e76b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59061 (ESTABLISHED)
Python     4051 hombit   97u  IPv4 0x437ad27cd597089b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59062 (ESTABLISHED)
Python     4051 hombit   98u  IPv4 0x437ad27cd59713ab      0t0  TCP 127.0.0.1:59036->127.0.0.1:59063 (ESTABLISHED)
Python     4051 hombit   99u  IPv4 0x437ad27cd7e7063b      0t0  TCP 127.0.0.1:59036->127.0.0.1:59064 (ESTABLISHED)
```

**Comment by dougbrn** [comment]
Ah, right. Yes it opens 8787 for the Dask Dashboard which you can connect to at 127.0.0.1:8787 to track progress https://docs.dask.org/en/latest/deploying-cli.html#diagnostic-web-servers. It does look like these are optional, and you may be able to turn it off within the Ensemble init call by also passing `dashboard_address=None`, as that gets passed along to the Dask client API

**Comment by hombit** [comment]
Could it be the default to listen `127.0.0.1:8787` instead of `::8787`?

**Comment by dougbrn** [comment]
I worry about a Dask extended package changing defaults under the hood, it may cause some dissonance between users expecations of Dask vs TAPE. We may just want to come up with an example configuration/setting to turn this off, and add that to our documentation?

**Comment by hombit** [comment]
By default `dask.distributed.Client` binds to `:8787`, see [docs here](https://distributed.dask.org/en/latest/api.html#distributed.LocalCluster). I see three options we have here:
1. Keep everything as is because the user would expect us to create default Dask client by default
2. Set `Client(dashboard_address="127.0.0.1:8787")` in `Ensemble` constructor and make it as explicit as possible - write it in the docs, make a constructor argument `dashboard_address="127.0.0.1:8787"`, etc.
3. Do not create any client by default, in this case threaded scheduler is used ([stackoverflow thread](https://stackoverflow.com/questions/71470336/using-dask-without-client-client#:~:text=If%20you%20don't%20have,memory%20space%20within%20a%20process)), which means a single CPU core will be used.

**Comment by dougbrn** [comment]
@hombit do you think this is fine to close, given #211 , or is there something else we should address here?

**Comment by nevencaplar** [comment]
After internal discussion, this seems fine to close
