### ISSUE TITLE
Identify Issues from TAPE Single Pixel Use Case

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#229]
@nevencaplar has produced this [example notebook](https://github.com/nevencaplar/JaxPeriodDrwFit/blob/main/Drw_per_i.ipynb) which applies TAPE to a "single pixel use case"

This issue is just to track the experience of running and debugging the notebook to identify various issues with correctness and usability in TAPE.

Some issues which @nevencaplar has identified in advance to me running the notebook myself:
* clarify documentation regarding from_parquet being able to consume directory paths in addition to file paths
* should we provide a better way for the user to identify shared columns between the source and object table?
* improve ability for a user to inspect which lightcurves are in the dataset
* fix errors involving time series sorting
* identify why NaN values are appearing in the timeseries
* fix the batch call to JaxPeriodDrwFit_instance.optimize_map

The above may be spun out into new issues and more may be documented here as well.

**Comment by dougbrn** [comment]
Some things I've ran into going down my own rabbit hole:

* We should add some kind of verbose flag to our analysis functions that can print to console (StructureFunction has a few instances), as in batch mode this can absolutely flood the output.
* The panstarrs magnitude conversions seemed strange, our unit tests should verify the computation is correct, but panstarrs mags are on order ~36, while ztf mags are around ~21-23

**Comment by wilsonbb** [comment]
@dougbrn has shared a notebook for the above [here](https://github.com/dougbrn/notebooks/blob/main/single_pixel.ipynb)

**Comment by wilsonbb** [comment]
Closing since I believe most of the above has been handled or is now tracked by other issues.
