### ISSUE TITLE
set_index calls quietly sort the Ensemble dataframes

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#242]
Discovered this recently that the default behavior of `dd.set_index` is to sort the dataframe based on the index values. This introduces a costly overhead to the workflow, and is needless when the user already has their data sorted. In principle, TAPE should be able to function without a sorted index. We should consider how to best implement this sorting functionality as an optional feature, and give users the ability to not do it for datasets that don't require it.

Additional note, if we are sorting the dataframes, it may be worthwhile to investigate generation of division information.

**Comment by hombit** [comment]
> We should consider how to best implement this sorting functionality as an optional feature, and give users the ability to not do it for datasets that don't require it.
The third option, which could be a default behavior, is checking the index to be sorted while reading the data. This is significantly cheaper than force-sorting, and would inform user if data must be sorted.

**Comment by dougbrn** [comment]
Yeah it would be nice if we could scan and check for that. I'm not sure how costly it will be since Dask will have to actually verify that it is sorted, and that is an operation that can't be done lazily.

**Comment by dougbrn** [comment]
Going to close this as the original scope of the issue has been addressed.
