### ISSUE TITLE
Initializing an ensemble and not providing ColumnMapper entry (e.g., provenance)

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#260]
When initializing an ensemble and not providing a column, the entries get filled with the default value. For instance, `provenance` gets filled with `survey_1`. This is confusing; rather I propose that the column is not created in such a case, or filled with `None`.

**Comment by dougbrn** [comment]
I think this was a special case for provenance, which is no longer in TAPE. Any other columns you've encountered this with @nevencaplar ? Otherwise think this can be closed.

**Comment by nevencaplar** [comment]
Closed, as recommended by the comment above.
