### ISSUE TITLE
Add Continuous Benchmarking for TAPE

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#266]
Recent changes to the LINCC Frameworks Python Project Template added [support for continuous benchmarking](https://lincc-ppt.readthedocs.io/en/latest/practices/ci_benchmarking.html) using GitHub Actions and airspeed velocity (ASV).

We should choose some lightweight datasets (possibly a lightweight version of the PLAsTiCC notebook created by 
@hombit). We may also consider using some heavier weight workflows where it may be more cost effective to have GitHub Actions running locally on Epyc.

**Comment by dougbrn** [comment]
Unassigning, may reassign in January, but @wilsonbb feel free to take a look at this if you end up doing any work on this next week

**Comment by dougbrn** [comment]
As of #340, this is now implemented in TAPE. I've just included two initial benchmarks to make sure everything is working. @nevencaplar, it's likely we'll want to build out this benchmarking suite, do you want to close this issue out and add a new issue? Or just track that in this issue?

**Comment by nevencaplar** [comment]
Yes, I agree. I will close this one and let's open new more dedicated tickets in the future.
