### ISSUE TITLE
Remove provenance machinery

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#292]
Provenance was added a while ago as a first step towards the multi-survey problem. However, that's further down the road for now and provenance is introducing some API bloat and slowdown. I'd advocate for scrapping it and re-implementing it fresh when there is more purpose to it.

**Comment by hombit** [comment]
I agree with that. I believe that, as it stands, the provenance column causes more confusion than it helps in solving multi-survey problems.
