### ISSUE TITLE
`Ensemble.batch` should support sorting by timestamp

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#316]
In TAPE we use an object ID as a table index in order to a) link the Source and Objects tables and b) ensure light curve cohesion among partitions (that source rows for a given light curve should be on the same partition). Unfortunately Dask lacks multi-index support, so we are not able to index on time as well. 

However for several custom functions expected to be provided to `Ensemble.batch`, it is expected for the data to be sorted by time. In practice, this is usually resolved by having the custom function call [`np.argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) on the data. We could arguably be calling this ourselves in `Ensemble.batch` or consider some other method for ensuring sorting by time while maintaining light curve cohesion.

**Comment by hombit** [comment]
I think it is a great idea to provide tooling for time-sorting the data, it would be nice to remove sorting data from here:
https://github.com/lincc-frameworks/tape/blob/1e8abfff5e0ea68327e87083f250d824274566d0/src/tape/analysis/feature_extractor.py#L81

However, I don't think that it is a good idea to make sorting to be a `batch` option, I would vote for having a separate method to pre-sort the data and an associated filed flag to track that the data is sorted. My reasons are: 1) sorting is quiet expensive, 2) it is enough to sort each partition once, 3) I wouldn't like to have one more kwarg in `batch`
