### ISSUE TITLE
Improve Per-Band Support in `Ensemble.batch`

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#317]
It's pretty typical for a user to want to perform per-band analysis via `Ensemble.batch`. Currently, a user can implement themselves in their custom function via array masking, but this is a) poor user experience b) gives the user opportunity to make an error.

Currently, `Ensemble.batch`'s `on` parameter could be used to allow the user to specify that the results should be grouped by both object ID and band. This yields an output table with a `MultiIndex` which (in my attempts at playing around with TAPE) initially works but eventually produces an error in the computation graph (unsurprising since Dask lacks [MultiIndex support](https://github.com/dask/dask/issues/1493)).

Possible solutions include:
* @dougbrn has suggested that we could consider using a pivot table in `Ensemble.batch` similar to what we do in `Ensemble.calc_nobs`
* Provide a specific `per_band` boolean parameter to `Ensemble.batch` that will take a user's output columns and create one per-each observed band (though we probably want to do some variation of the above anyway).

**Comment by hombit** [comment]
I like this idea, it would simplify feature extraction support. However, I see some discussion points here. Would we like user to select a list of bands? Do we really want it in `batch`?

1. I don't really understand the first proposal...
2. It would make `batch` to be quiet complicated, especially in `meta` specification by user and return types. I would think about alternatives, for example having a separate `batch_per_band` or something like that.
