### ISSUE TITLE
Pass Dask Dataframe from LSDB->TAPE without reset_index

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#318]
One approach of providing results from LSDB to TAPE is to:

1. Create an `Ensemble` object that reuses LSDB's Dask client
2. Call `Ensemble.from_dask_dataframe` to load the underlying Dask dataframes. 

However currently `Ensemble.from_dask_dataframe` yields an error unless `reset_index` is called on its source and object frame arguments. We should be able to load the frames regardless of their existing index.

**Comment by hombit** [comment]
+1 to this, I had all the same issues with the Plasticc notebook

**Comment by wilsonbb** [comment]
This issue has been resolved for [https://github.com/dirac-institute/ZTF_FG_BoyajianSearch/blob/main/analysis/notebooks/demos/zubercal-tape-demo.ipynb](Boyajian Search notebook) when using LSDB `main` since the index/meta is no longer malformed for the object table created by LSDB.

@hombit what issue are you still seeing? In my [version of your notebook](https://github.com/lincc-frameworks/notebooks_lf/blob/main/plasticc-eclipsing-binaries.ipynb), I'm able to call `Ensemble.from_dask_dataframe` without having to call `reset_index` on the provided dataframes. Did I end up doing something differently or is there another version of the issue I'm not considering?

**Comment by hombit** [comment]
@wilsonbb I think you are right and it is fixed now. Sorry for the noise

**Comment by wilsonbb** [comment]
No worries :)
