### ISSUE TITLE
Try latest numpy version on TAPE docs (eztao especially)

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#324]
Numba claims to [now support](https://github.com/numba/numba/pull/9105) numpy v1.25.0, we should see if we can drop the pin to older numpy versions. @nevencaplar wants to look into this.

**Comment by nevencaplar** [comment]
Closed with https://github.com/lincc-frameworks/tape/commit/e7bea171584f7d4af29e8eff2d1d090ffaf361e3
