### ISSUE TITLE
Add possibility to do computation on subset of the dataset

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#356]
A highly needed functionality seems to be the ability to any computation of a subset of the data. At the moment, the closest thing that is possible is to operate via the .head() command. This is problematic as it a) does not allow to operate on a custom subselection of the data b) loads the data into memory.
Implement better methods to access and operate on subsets of data. Do this work in a manner that is consistent with any potential LSDB implementation.

**Comment by dougbrn** [comment]
Implementation Notes
=================
Theres a few ways to approach this. I'll use this as a space to log some design possibilities/choices.

Approach 1: Wrap [Dask.dataframe.sample](https://docs.dask.org/en/latest/generated/dask.dataframe.DataFrame.sample.html)
-----------
Sample does largely what we want here, offering a fractional value for the user to specify to determine the subset of the dataframe returned by dask. I think this would be an ensemble-level function that calls this on the object table, and syncs the subset object to the source to remove all discarded objects. There's some question of if we'd want to propagate this filter to the result frames, where I think the answer is ideally, yes, but it's less clear how straightforward this would be in practice (just with how divergent result frames can theoretically be). Perhaps we can check for result frames that are indexed by the _id_col and do some kind of pseudo sync against them.

Approach 2: Leverage Partitions
------------
At scale, partitions gives us a shortcut to subselecting our data, as getting ~10% of a dataset with 10 partitions is just randomly selecting a single partition (roughly). @hombit has shown how this can be done in the code example below. This should be significantly faster than the first approach, with the caveat that it will only work in cases where we have many partitions and you won't have great control over the exact number of returned objects.
```
n_object_partitions = 5
# # off by one because we need last partition **end**
last_object_division = objects._ddf.divisions[n_object_partitions+1]

n_joined_source_partitions = np.searchsorted(joined_sources._ddf.divisions, last_object_division) - 1

print(f'{n_object_partitions = } / {objects._ddf.npartitions}')
print(f'{n_joined_source_partitions = } / {joined_sources._ddf.npartitions}')

object_frame = objects._ddf.partitions[:n_object_partitions]
source_frame = joined_sources._ddf.partitions[:n_joined_source_partitions]
```

Conclusion
-----------
I think a good potential way forward is for both approaches above to be implemented as their own functions. We have a faithful wrapping of `dask.dataframe.sample` for fine control of subsets in `Ensemble.sample`. We also have a partition sub-selector implemented in `Ensemble.select_partitions` which is preferred in use cases where a user is trying to work at scale. It's possible it would be confusing to have both of these available, but I think it's preferable than having one do-it-all function here.

In both cases, we'll want to return a new ensemble object to not overwrite the existing ensemble.
