### ISSUE TITLE
Guarantee Lightcurve Cohesion from LSDB

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#359]
When loading from LSDB to TAPE, we assume that lightcurve cohesion is guaranteed by having mutually exclusive divisions set for an index on a per-object ID field.

From a discussion with @delucchi-cmu, this may not be guaranteed, and we should verify if that's the case and what our options might be.

**Comment by hombit** [comment]
I'm not sure I understand this problem.

LSDB's `Catalog.join` should give us a source table good to go with the object table it was joined with. Currently, while LSDB misses margin (association) cache implementation, we may have problems with some object's sources to be missed in this join, but I believe it will be solved on LSDB's side eventually.

**Comment by hombit** [comment]
Margin cache: https://github.com/astronomy-commons/lsdb/issues/51

Association cache: https://github.com/astronomy-commons/lsdb/issues/59

**Comment by wilsonbb** [comment]
Per Kostya's reason cited above, a workflow of using Catalog.join to generate the source table addressed @delucchi-cmu's potential concerns.

Closing since this is the main workflow we're currently using.
