### ISSUE TITLE
Rewrite start of Home page  ``Intro to documentation’’

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#365]
The start of the TAPE documentation https://tape.readthedocs.io/en/latest/index.html emphasizes working with LSST timeseries data. I believe there is a danger that an user might be disincentivized to use it for other big surveys. I recommend changing it to something more in spirit to ``working with large amount of data, towards LSST’’

**Comment by wilsonbb** [comment]
Closed by https://github.com/lincc-frameworks/tape/pull/407
