### ISSUE TITLE
Add a section: “Loading from LSDB” in the documentation 

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#367]
Add a section: Loading from LSDB in the documentation. Possibly need to create a small LSDB catalog from the data and load to TAPE

**Comment by dougbrn** [comment]
@nevencaplar [this notebook](https://tape.readthedocs.io/en/latest/tutorials/working_with_hipscat_and_lsdb.html) was added as part of #374, let me know (no rush) if you think it's good enough to close this ticket with.
