### ISSUE TITLE
Add example for ens.persist in the documentation

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#368]
ens.persist(), mentioned in [https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Dask-and-"Lazy-Evaluation"](https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Dask-and-"Lazy-Evaluation") does not have an example of the use. It would be valuable to have a small example at that location in the documentation.

**Comment by dougbrn** [comment]
Resolved by #395. This is implemented in a new notebook that deprecates the old "working with the ensemble notebook"
