### ISSUE TITLE
Keeping the Object and Source tables in Sync - has subsections which are not relevant

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#370]
[Keeping the Object and Source tables in Sync](https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Keeping-the-Object-and-Source-Tables-in-Sync) - has subsections which are not relevant. It is unclear to me how they ended up here, but the subsections do not seem to be relevant. Resolve by moving the subsections to better locations.

**Comment by dougbrn** [comment]
Fixed in #388
