### ISSUE TITLE
Break up the "Working with the Ensemble Tutorial"

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#392]
This tutorial is way to long and conflates common dataframe operations with working on the Ensemble object. We should split this into two separate tutorials:
* Common Dataframe Operations -- @dougbrn 
* Understanding the TAPE Ensemble -- @wilsonbb

**Comment by wilsonbb** [comment]
https://github.com/lincc-frameworks/tape/pull/395 and https://github.com/lincc-frameworks/tape/pull/401 close this issue
