### ISSUE TITLE
Load pre-sorted datasets in documentation notebooks

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/tape#397]
In our TAPE documentation notebooks, we encounter warnings when loading datasets where divisions are not set.

<img width="1046" alt="Screenshot 2024-03-14 at 3 01 46 PM" src="https://github.com/lincc-frameworks/tape/assets/22227694/a19058c5-b15e-4c5b-81f3-3eee39ac537c">

We can ensure that the Ensemble has divisions and avoids those warnings by using `sorted=True` for pre-sorted data or `sort=True` for unsorted data.

To avoid having to sort data in our tutorial notebooks, we can pre-sort our datasets (like s82_rrlyrae which is currently unsorted) and then use the `sorted=True` flag

**Comment by dougbrn** [comment]
I went about this a slightly different way, by having the from_dataset function sort them as part of the ingest function. I think we can close this as a result, and with #415.
