### ISSUE TITLE
Find number of observations per band in ensemble without computing

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#53]
[Ensemble.count](https://lsstseries.readthedocs.io/en/latest/autoapi/lsstseries/ensemble/index.html#lsstseries.ensemble.Ensemble.count) at the moment gives number of observations for a total lightcurve, i.e., all bands together. Implement that it gives a count per band, if desired.

**Comment by dougbrn** [comment]
The object table now natively tracks nobs by band.
