### ISSUE TITLE
Basic API improvements - generate new columns

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#64]
Given the results of some analysis, have an API or ``easy'' ability to append the new results to the ensamble table (object table) as a custom column.

**Comment by drewoldag** [comment]
Just read this and I don't have any context, but the approach that works well in relational databases is to have a couple of thin ancillary tables indexed on `Object.id`. 
```
**ancillary_data**
object_id BIGINT,
data_type_id INT,
value <type>

**data_types**
data_type_id INT,
data_type_representation <what type of data, INT, FLOAT, CHAR, ...>,
description <STRING>
```

**Comment by dougbrn** [comment]
Assign addresses this, we may have more structured functions as well but I think the spirit of this issue is addressed. Feel free to reopen if you disagree :)
