### ISSUE TITLE
Accept lightcurves from multiple surveys

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#67]
The package needs to be able to accept data from multiple surveys. It remains the open questions how best to handle this case - is it just duplicating all columns, renaming so that we can distinguish which column came from which survey? There will be many nans, is that ok?

**Comment by dougbrn** [comment]
We now have provenance columns to help track source, but API to take in from two disparate data sources is still non-existent

Potential blocker of #140

**Comment by dougbrn** [comment]
We're able to support multi-survey datasets via LSDB at this time. While more infrastructure for multi-provenance work will be good down the road, the scope of this issue can be considered completed.
