### ISSUE TITLE
How to run on cloud

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#69]
How to run on a cloud - we expect that a lot of our code will be used in some sort of cloud. What are the challenges in implementing lsstseries code to run on a cloud, and what functionality updates need to be made? This ticket is to investigate these issues and make recommendations for that effort.

**Comment by dougbrn** [comment]
Tangentially related, reading data from the cloud. fsspec is the likely string to pull

**Comment by nevencaplar** [comment]
This ticket is poorly defined and deprecated at this point. We need to tackle this in the future, but this is to done in dedicated and better defined tickets.
