### ISSUE TITLE
Identify small yet useful dataset for tutorials and examples

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#72]
We should have a relatively small, yet realistic dataset which we can use for testing and tutorials. Identify such sample and make it usable for developers.

**Comment by nevencaplar** [comment]
Preliminary I suggest:

**Comment by dougbrn** [comment]
We've created a new repository to collect these datasets, with S82 RR Lyrae and S82 QSOs in first: https://github.com/lincc-frameworks/tape_benchmarking

**Comment by dougbrn** [comment]
We have some quick datasets on hand now, we should open more targeted issues for any additional datasets we'd like to add.
