### ISSUE TITLE
LSDB/HiPSCat support

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/tape#88]
An action towards #67 is adding support for the [HiPSCat format](https://github.com/astronomy-commons/hipscat), which will be one of the outputs of LSDB.

Support for this involves two main items:
* Implementing a custom loader function that uses a hiPSCat tool to read through their hierarchical directory structure
* Re-indexing the output to be on object id, instead of the custom HiPSCat index.

Other items to be mindful of:
* Ensuring some provenance column is made/kept, to be able to disentangle each survey from the ensemble if needed
* Adding the option to keep the hipscat index as a column, for possible backwards compatibility with LSDB
* Eventually, adding a loader function for the LSDB dataframe directly, avoiding a write to disk.

**Comment by dougbrn** [comment]
#93 Addresses the basics of loading a hive-like directory structure. A future PR will address more hipscat-specific integration, we most likely will want to use LSDB code to facilitate initial joins and are therefore a bit blocked until that functionality makes its way into the main branch of LSDB

**Comment by nevencaplar** [comment]
Closing this, while #339 aims to better capture the needed items.
